name: v1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_swiper: ^1.1.6

  url_launcher: 

  provider:

  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png" 


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  change_app_package_name:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - textFiles/grandmother.txt
    - textFiles/aboutlove.txt
    - textFiles/achild.txt
    - textFiles/astory.txt
    - textFiles/boarding.txt
    - textFiles/bruno.txt
    - textFiles/children.txt
    - textFiles/dream.txt
    - textFiles/fullfathom.txt
    - textFiles/gingerbread.txt
    - textFiles/gods.txt
    - textFiles/gretel.txt
    - textFiles/hurried.txt
    - textFiles/jack.txt
    - textFiles/jacob.txt
    - textFiles/lamentation.txt
    - textFiles/lastvoyage.txt
    - textFiles/little.txt
    - textFiles/purgatory.txt
    - textFiles/telltale.txt
    - textFiles/travelling.txt
    - textFiles/twolongterm.txt
    - textFiles/womens.txt
    - textFiles/1.txt
    - textFiles/2.txt
    - textFiles/3.txt
    - textFiles/4.txt
    - textFiles/5.txt
    - textFiles/6.txt
    - textFiles/7.txt
    - textFiles/8.txt
    - textFiles/9.txt
    - textFiles/10.txt
    - textFiles/11.txt
    - textFiles/12.txt
    - textFiles/13.txt
    - textFiles/14.txt
    - textFiles/15.txt
    - textFiles/samples.txt
    - textFiles/road.txt
    - textFiles/past.txt
    - assets/logo.png
    - assets/heritageofwords.jpg
    - assets/meaning.jpg
    - assets/icon.png
    - assets/place.png
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

